gwasPheno:
 - MI
 - LDL

wesPhenoLin:
 - LDL

wesPhenoLog:
 - MI
 - T2D

# WES Lookup
# python 2.7
geneWES:
 phizer_GDF2_LLRK2:     [GDF2, LRRK2]
 test_TRIB1_APOE_MAFB:  [TRIB1, APOE, MAFB]

# .sample file
# order: covariates before phenotypes
dotSample:
 age:           [ AGE,   C]
 gender:        [ SEX,   D, male]
 c1:            [ PCA1,  C]
 c2:            [ PCA2,  C]
 c3:            [ PCA3,  C]
 c4:            [ PCA4,  C]
 c5:            [ PCA5,  C]
 c6:            [ PCA6,  C]
 c7:            [ PCA7,  C]
 c8:            [ PCA8,  C]
 c9:            [ PCA9,  C]
 c10:           [ PCA10, C]
 status:        [ MI,    B, control]
 ldlmgdl:       [ LDL,   P]


# phenotypes from universal sample file
# not PCA and not BATCH (hardcoded for now)
wesAnnoPhe:
 status:        [MI,  B, control ]
 dm_h:          [T2D, B, 0]
 ldlmgdl:       [LDL, P]
 age:           [AGE, C]
 gender:        [SEX, D, male]


# Gene-locuszoom plots for phenotypes
#

LDL:
 - EHBP1
 - BRCA2
 - FN1

HDL:
 - ANGPTL1
 - CITED2
 - STAB1

# number of chunks per chromosome
chrChunk:
 - 55
 - 54
 - 45
 - 44
 - 41
 - 40
 - 37
 - 35
 - 34
 - 33
 - 32
 - 32
 - 25
 - 24
 - 23
 - 22
 - 21
 - 20
 - 17
 - 15
 - 12
 - 12

